export const Types = {
  RegisterUser: "sign_up",
  LoginUser: "Login",
  LogoutUser: "LogoutUser",
  FetchCompanies: "loadCompanies",
  FetchAccounts: "FetchAccounts",
  CreateAccount: "CreateAccount",
  FetchTransaction: "FetchTransactions",
  FetchItems: "Fetch Items",
  FetchStocks: "Fetch Stocks",
  CreateStock: "Create Stock",
  CreateTransaction: "CreateTransaction",
  AddTransactionCategory: "AddTransactionCategory",
  GetTransactionCategory: "GetTransactionCategory",
  CheckLogedInUser: "checkloggedinuser",
  GetUser: "getUser",
  FetchItem: "fetchItem",
  addItem: "addItem",
  getItemCategory: "getItemCategory",
  fetchStockUnits: "fetchStockUnits"
};
